[server]
address = '0.0.0.0'
port = '8501'
enableWebsocketCompression=false
baseUrlPath = '/app/'
enableCORS = false
enableXsrfProtection = false

[browser]
serverPort='443'
serverAddress='chat.dialog.guide'
gatherUsageStats = false